---
# This playbook is for ubuntu LTS machines 

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ubuntu

  roles:
    - common

- name: configure and deploy the AWS CLI and Cloudwatch tooles
  hosts: aws
  remote_user: ubuntu

  roles:
    - cloudwatch 

- name: configure and deploy the Cloudwatch Logs with most common logs 
  hosts: aws
  remote_user: ubuntu

  roles:
    - cwlogs
- name: configure and harden bastion host
  hosts: bastion
  remote_user: ubuntu

  roles: 
  - bastion

- name: configure interactive data users
  hosts: interactive
  remote_user: ubuntu
  
  roles:
  - interactive 
