---
# Removes non essential packages from debian system
- apt: pkg=telnet state=absent purge=yes
- apt: pkg=ftp state=absent purge=yes

# removes default users from scp 
- file: path=/usr/bin/scp owner=www-data group=www-data mode=0644

# Improving IP security in '/etc/systctl.d/10-network-security.conf'
- copy: src=10-network-security.conf dest=/etc/sysctl.d/10-network-security.conf owner=root group=root mode=644 backup=yes

  notify:
  - restart procps

